# Generated by Django 3.2.3 on 2021-07-03 04:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchorder',
            name='processed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_clerk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lunchorder',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='employee_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='receipt',
            field=models.FileField(help_text='Select a pdf file', upload_to='claims/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveadjustment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=100),
        ),
        migrations.AlterField(
            model_name='lunchorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mileageclaim',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mileageclaim',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=100),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salaryadvance',
            name='status',
            field=models.CharField(default='Pending Approval', max_length=100),
        ),
    ]
